spring:
  sql:
    init:
      mode: always #reset/new table
      platform: mysql
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true # after ddl-auto, data.sql query apply
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  iss : rod.com
  exp: 24 * 60 * 60 * 1000
  secret : keykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyet