spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://3.34.165.98:3306/sedb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
      springframework:
        security: DEBUG
        web: DEBUG
        data: DEBUG
        hibernate: DEBUG
        jpa: DEBUG
        sql: DEBUG
        jwt: DEBUG
jwt:
  iss: lawmate.site
  expiration: 86400000 # 24 * 60 * 60 * 1000 in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds
  secret: keykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyet
