spring:
  sql:
    init:
      mode: always #reset/new table
      platform: mysql
  application:
    name: api
  datasource:
    url: jdbc:mysql://3.34.165.98:3306/roddb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
=======
      ddl-auto: update
>>>>>>> 794b7870939c364c52a333f1ac5d91712c8641c0
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true # after ddl-auto, data.sql query apply
#    open-in-view: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  iss : rod.co.kr
  exp: 24 * 60 * 60 * 1000
  secret : keykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyetkeykeyet