services:
  database:
    container_name: mysql-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/lawmatedb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/lawmatedb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/lawmatedb/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=lawmatedb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"