services:
  database:
    container_name: mongodb-container
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mydb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - rootnet
  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mongodb://db-container::27017/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - rootnet
networks:
  rootnet:
    driver: bridge