services:
  database:
    container_name: mongodb-container
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=lawmatedb
    restart: always
    ports:
      - "27017:27017"